WorkLoggerBundle\Entity\User:
  exclusion_policy: ALL
  properties:
    firstName:
      expose: true
      groups: [USER_DETAILS, USER_PROFILE, USER_BASIC]
    lastName:
      expose: true
      groups: [USER_DETAILS, USER_PROFILE, USER_BASIC]
    phone:
      expose: true
      groups: [USER_DETAILS, USER_PROFILE, USER_BASIC]
    department:
      expose: true
      groups: [USER_DETAILS, USER_PROFILE, USER_BASIC]