WorkLoggerBundle\Entity\RefreshToken:
  type: entity
  table: refreshtoken
  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  manyToOne:
    client:
      targetEntity: WorkLoggerBundle\Entity\Client
      joinColumn:
        nullable: false
    user:
      targetEntity: WorkLoggerBundle\Entity\User

  lifecycleCallbacks: {  }
