services:
  client_validate:
    class: ApiBundle\Validator\Constraints\ClientIdValidator
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      -  { name: validator.constraint_validator, alias: client_validate }

  user_validate:
    class: ApiBundle\Validator\Constraints\UserUniqueValidator
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      -  { name: validator.constraint_validator, alias: user_validate }