services:
  work_logger.user_factory:
    class: WorkLoggerBundle\Model\UserFactory

  work_logger.token_factory:
    class: WorkLoggerBundle\Model\AccessTokenFactory
    arguments: ["@doctrine.orm.entity_manager", "@fos_oauth_server.server"]

